version: 0.2
phases:
  install:
      runtime-versions:
        dotnet: latest
        
  pre_build:
    commands:
      - cd AwsApiProject/src/AwsApiProject
      - echo Restore started
      - dotnet restore -p:PublishReadyToRun=true AwsApiProject.csproj
      
  build:
    commands:
      - echo build started
      - dotnet publish ---no-restore -p:PublishReadyToRun=true -c release -o ./build_output AwsApiProject.csproj
