version: 0.2
phases:
  install:
     commands:
      - /usr/local/bin/dotnet-install.sh --channel LTS
  pre_build:
    commands:
      - echo Restore started
      - dotnet restore AwsApiProject.csproj
  build:
    commands:
      - echo build started
      - dotnet publish -c release -o ./build_output AwsApiProject.csproj
