version: 0.2
phases:
  install:
      runtime-versions:
        dotnet: latest
        
  pre_build:
    commands:
      - cd AwsApiProject/src/AwsApiProject
      - echo Restore started
      - dotnet restore AwsApiProject.csproj
      
  build:
    commands:
      - echo build started
      - dotnet publish -c release -o ./build_output AwsApiProject.csproj
artifacts:
  files:
    - '**/*'
  name: DevOpsArtifact
 
